# Generated by Django 6.0.7 on 2026-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymetric',
            name='buyers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='cancelled_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='cancelled_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='existing_buyers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='new_buyers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='potential_buyers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='product_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='refunded_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='refunded_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='repeat_purchase_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='sales_rebate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
