# Generated by Django 6.0.7 on 2026-09-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('shopee', 'Shopee'), ('lazada', 'Lazada'), ('tiktok', 'TikTok Shop')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('orders', models.IntegerField(default=0)),
                ('visitors', models.IntegerField(default=0)),
                ('pageviews', models.IntegerField(default=0)),
                ('cvr', models.FloatField(default=0.0)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('platform', 'date')},
            },
        ),
    ]
