# Generated by Django 6.0.7 on 2026-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dailymetric_buyers_dailymetric_cancelled_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('lazada', 'Lazada'), ('shopee', 'Shopee'), ('tiktok', 'TikTok Shop')], db_index=True, default='lazada', max_length=20)),
                ('transaction_date', models.DateField(db_index=True)),
                ('transaction_type', models.CharField(db_index=True, max_length=100)),
                ('fee_name', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('seller_sku', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('lazada_sku', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_in_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('statement', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('paid_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('order_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('order_item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('order_item_status', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transaction_date', 'order_no'],
            },
        ),
    ]
